### ISSUE TITLE
Loading from relative paths

### ISSUE THREAD

**Issue by leonardorame** [cornerstonejs/cornerstoneWebImageLoader#22]
Hi, I would like to know how can I define a list of imageIds pointing to relative paths.

For example:

       var imageIds = [
         '/image/1791922.jpg',
         '/image/1791925.jpg',
         '/image/1791928.jpg'
       ];

Breaks with error `Error: loadImageFromImageLoader: no image loader for imageId`

But if I add `http://<IP_OF_SERVER>` it loads wonderfully.

Any hint?.

**Comment by dannyrb** [comment]
Each registered image loader has an associated `scheme`. The `webImageLoader` is registered to use the `http:` and `https:` `scheme`s. You could fork/modify the `cornerstoneWebImageLoader` to work with relative paths by:

- Registering the `webImageLoader` with the `web:` scheme
- Updating the loader to use relative paths when querying for images
- Calling load image using an imageId like: `web:/image/somefilename.jpg`

Let me know if you need additional clarification or if you have specific questions.

**Comment by leonardorame** [comment]
Great. I don't like to fork/modify sources, so we did a workaround by concatenating `http://" + window.location.host + /relative/path/to/image';`

**Comment by dannyrb** [comment]
FWIW, if you create a solid PR w/ unit tests, I'd be more than happy to merge the ability to use relative paths with the `cornerstoneWebImageLoader`. Feel free to close this issue if we're all good here :+1:

**Comment by leonardorame** [comment]
Yes, that's the best approach, i'll take a look at it and send a PR.
