### ISSUE TITLE
404 of cornerstoneWebImageLoader

### ISSUE THREAD

**Issue by Delink-D** [cornerstonejs/cornerstoneWebImageLoader#27]
Is this link active? when I load i get a 404
https://raw.githubusercontent.com/cornerstonejs/cornerstoneWebImageLoader/master/dist/cornerstoneWebImageLoader.js

**Comment by dannyrb** [comment]
`cornerstoneWebImageLoader` is one of the less used libraries, and we're already a bit strapped for resources. Most library changes come from 3rd party pull requests (users like you). If you create a PR to clean up the README, I'd be more than happy to review + merge 👍
