### ISSUE TITLE
Applying Filters on Images loaded

### ISSUE THREAD

**Issue by NicholaAlkhouri** [cornerstonejs/cornerstoneWebImageLoader#28]
Hello,

Is there a way to apply some filters on the loaded images, for example (Sharpness).
This filter usually implemented using a mathematical method to change the image pixels, using a 3d matrix.

Regards.

**Comment by dannyrb** [comment]
@NicholaAlkhouri you can apply whatever filters you want in `createImage` on the mapped pixelData. You could also implement a custom renderer in `cornerstone-core`
